# top level stuff you probably don't need to touch
# highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://www.davidh83110.com
baseurl: /
title: David Hsu
author: David Hsu
description: HomePage
avatar: assets/images/avator.png
email: davidh83110@gmail.com
github: davidh83110 # username
#twitter: davidh83110
linkedin: davidh83110
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
disqus: davidh83110
google_analytics: UA-85468802-2


# needed for travis-ci build
exclude: [vendor]
